# pack -> list of (prompt text, words). Words: lowercase a-z, 3+ letters.
PACKS = {
'meme': [
("A meme or internet joke", "doge pepe stonks yeet rickroll karen chad simp cringe based sus vibe mood lol rofl oof bruh fail troll noob meme viral gif emoji flex lit rizz drip cap salty thicc woke dank sheesh yolo fomo bae"),
("Something you do on social media", "scroll like share post tweet follow unfollow block mute stream tag comment reply repost doomscroll lurk troll flex vlog selfie filter hashtag ghost cancel trend swipe upload download viral react"),
("An emoji you spam", "skull heart fire laugh cry smile wink cool angry clap pray eyes party poop ghost alien robot rocket star cloud rain sun moon pizza taco cake crown ghost devil angel"),
("Something that is 'sus'", "imposter impostor vent crewmate sabotage vote eject alibi liar shady fishy suspect culprit trick lie fake spy sneak snitch rat mole traitor shifty crooked dodgy"),
("A thing that goes viral", "dance song video challenge prank recipe trend photo fail clip meme cat dog baby hack tweet post filter sound remix cover stunt flashmob duet skit"),
("A video game everyone memes about", "minecraft fortnite roblox tetris pacman zelda mario sonic pokemon doom portal halo skyrim terraria among valorant overwatch apex fallout witcher celeste hades undertale"),
("Something a 'boomer' would say", "back sonny kids phone lawn cheque fax vhs radio dial landline newspaper disco vinyl typewriter antenna cassette rotary telegram postcard stamp"),
("A 'main character' thing to do", "walk dance cry sing run laugh stare wander journal film window rain train coffee headphones sunset skyline rooftop poetry convertible"),
("A reaction in the group chat", "lol lmao rofl omg wtf bruh huh nope yikes oof dead ded yeet wow nice cap fire based mood same facts sheesh sus kek hype gasp"),
("Something that is 'cringe'", "karaoke fedora tiktok mime cosplay pickup prank rap poem skit duet crush dance mullet emo nickname selfie jargon pun dad awkward blush spam"),
("A thing in a 'gamer setup'", "mouse keyboard monitor chair headset mic webcam desk lamp light router console controller joystick gpu cpu fan led cable mousepad speaker stand dock"),
("A famous internet animal", "doge grumpy cat dog frog keyboard capybara fish bird goat llama sloth hamster panda duck seal otter alpaca pug corgi husky chonk bear owl"),
("Something you 'rage quit' over", "lag glitch bug ping death fall loss boss lagspike disconnect crash timeout camper hacker cheater noob combo rng loot drop respawn trap puzzle"),
("A streamer or YouTuber thing", "stream sub donate clip raid chat emote hype vod mod bits sponsor intro outro thumbnail vlog subscribe bell channel live upload patreon merch"),
("A word you'd see in a 'tier list'", "best worst top mid trash god bronze silver gold diamond rank banger bad good elite cool lame legend meh tier rated hot"),
("A popular snack for a movie night", "popcorn candy chips nachos pizza soda pretzel cookie chocolate gummy taco fries jerky pickle cheese cracker cupcake donut licorice marshmallow"),
("A 'plot twist' ingredient", "twin clone ghost dream secret traitor mask spy memory heir curse portal prank villain hero ally letter clue lie reveal tape amnesia"),
("An app on your phone", "camera maps music mail notes clock weather calendar photos calculator wallet browser store messages phone settings health fitness podcast news video game reels"),
("Something you do when bored", "scroll nap snack doodle pace sigh doomscroll stare daydream pickup wander hum tap fidget channel flip text call read sleep clean game"),
("Slang that means 'cool'", "lit fire dope sick rad neat swell slick fresh epic wicked groovy gnarly tight smooth awesome killer bad boss tubular crisp"),
("A reason to say 'no cap'", "truth fact real honest legit proof swear serious sincere straight exact sure certain frank plain solid"),
("A creature from internet horror lore", "slenderman backrooms smile dog mimic skinwalker wendigo rake siren head grinning jeff creepypasta ghost entity shadow doll puppet clown"),
("A thing 'NPC' characters do", "stand wave walk repeat nod greet loop idle patrol shop sell talk guard wander blink spawn despawn follow quest sign repeat"),
("A 'trend' from the last decade", "fidget spinner planking harlem shake ice bucket dab floss hoverboard slime mannequin pumpkin latte avocado toast unicorn tiktok dalgona bottle flip"),
("A word you use in a hype message", "lets go yes win fire epic wow huge insane crazy legend goat king queen boss massive clutch ace perfect champ banger"),
("Something that gets 'canceled'", "show tour plan flight meeting game contract trip date class party wedding season subscription order event concert"),
],
'fantasy': [
("A fantasy creature", "dragon unicorn griffin phoenix goblin troll ogre elf dwarf orc wyvern hydra centaur minotaur pegasus sphinx banshee kraken golem imp pixie sprite fairy gnome yeti basilisk cyclops harpy chimera mermaid giant"),
("A magical item", "wand staff amulet ring cloak orb tome scroll potion crown grimoire talisman charm rune crystal relic chalice lantern mirror sword shield boots horn gauntlet scepter"),
("A spell or magic action", "conjure summon curse hex bless heal burn freeze smite banish cast charm enchant levitate vanish shield ward blink teleport transmute illuminate dispel shapeshift"),
("A place in a fantasy world", "castle tower dungeon cave forest keep realm kingdom village temple ruin swamp mountain citadel fortress crypt tavern harbor valley glade abbey bridge throne lair"),
("A fantasy hero's weapon", "sword bow axe dagger spear staff mace hammer shield lance crossbow club whip trident blade sling flail halberd rapier scimitar wand"),
("Something in a wizard's tower", "cauldron scroll book potion orb staff owl cat candle bottle skull crystal mirror herb telescope quill ink desk chest globe map robe hat"),
("A type of magic user", "wizard witch sorcerer mage warlock druid shaman cleric priest sage seer oracle enchanter necromancer alchemist conjurer monk bard summoner"),
("A dragon's treasure", "gold gem coin jewel ruby pearl crown goblet chalice amulet diamond silver idol sapphire emerald relic ring chest hoard medal tiara"),
("A kind of potion", "healing poison love luck speed strength sleep fire frost courage invisibility growth shrink antidote elixir tonic brew draught mana stamina"),
("A tavern order", "ale mead stew bread cheese roast wine cider pie soup broth ham tart honey mutton bacon porter lager rum"),
("A fantasy race or folk", "elf dwarf orc goblin human halfling gnome troll giant faun fairy tiefling dragonborn kobold ogre imp nymph satyr centaur"),
("A knight's gear", "armor helm shield sword lance spurs gauntlet cape horse banner mail visor greaves saddle crest tabard plate boots belt"),
("A name for a magic school subject", "alchemy divination conjuring healing illusion necromancy enchanting evocation abjuration runes potions herbology astronomy charms"),
("A creature you'd find in a dark forest", "wolf owl bat spider raven fox bear boar stag snake elk moth goblin wraith ent troll witch hag sprite"),
("A royal court role", "king queen prince princess duke earl baron knight jester squire page steward bishop herald regent advisor chancellor marshal cupbearer"),
("A quest item", "key map scroll gem sword shield amulet relic orb crown chalice rune idol potion lantern ring horn feather egg"),
("Something an elf might be good at", "archery stealth magic singing healing tracking dancing poetry crafting wisdom forestry riding herbs music climbing"),
("A fantasy beast you can ride", "horse dragon griffin pegasus unicorn wolf boar bear eagle drake wyvern elk stag camel hippogriff mammoth"),
("A thing found in a dungeon", "trap chest key torch skeleton rat spider bone coffin chain door altar throne cell stairs puzzle lever rune ooze"),
("A dark lord's minion", "orc goblin imp wraith ghoul skeleton zombie bat troll witch demon cultist spider wolf specter"),
("A magical element", "fire water earth air ice lightning shadow light storm wind frost metal nature void spirit arcane thunder"),
("A mythical place", "atlantis eden avalon olympus valhalla elysium asgard camelot shangrila hades tartarus nirvana utopia oasis"),
("Something a bard does", "sing play tell strum whistle rhyme hum perform joke juggle compose recite lute dance tale story verse"),
("A fairy tale object", "slipper mirror apple spindle beanstalk lamp pumpkin crown tower glass castle gingerbread poison thorn rose"),
("A word about a quest or adventure", "journey trek voyage hunt raid siege march battle trial riddle peril glory treasure mission odyssey crusade expedition"),
],
'cyber': [
("A piece of computer hardware", "mouse keyboard monitor router modem motherboard cpu gpu ram fan drive disk cable port chip server switch webcam printer scanner speaker battery charger"),
("A programming word", "code loop array string bug class function variable debug compile script stack queue syntax module api list sort node tree commit branch merge"),
("A thing hackers do", "hack crack phish breach exploit spoof sniff probe scan inject decrypt encrypt bypass pwn leak trace infiltrate steal boot"),
("A cyberpunk gadget", "implant visor drone neon hologram cyberdeck chip jack hoverbike blade glove goggles wires spike mask arm eye link"),
("Something about the internet", "web site page link email chat cloud server router wifi browser domain stream upload download packet host bandwidth cookie cache"),
("A robot or AI word", "robot droid android cyborg bot mech drone ai neural circuit servo sensor logic machine algorithm program engine core"),
("A sci-fi spaceship part", "hull engine thruster cockpit airlock cargo reactor shield radar cannon wing bridge hatch bay console beacon dock fuel nozzle"),
("A security term", "firewall password token lock key cipher vpn proxy virus malware worm trojan patch antivirus auth login encrypt secure alarm badge"),
("A futuristic city thing", "neon tower skyline monorail hover drone billboard tunnel grid sprawl plaza arcade station elevator skyway megacorp slum alley"),
("A data or file word", "file folder zip byte bit data log cache backup record table index archive backup drive disk format sector bin"),
("A gaming-tech term", "pixel sprite polygon texture shader frame render mod patch lag ping fps cutscene loot spawn avatar hitbox engine level"),
("A thing on a keyboard", "key shift enter space tab escape delete caps alt control arrow home end insert function number letter return backspace"),
("A network word", "node hub switch router packet port host server client lan wan ping hop link gateway mesh dns proxy cable"),
("A cyber crime or scam", "phishing scam fraud spam ransom theft breach leak catfish spoof clone skimming hijack extortion fake swindle"),
("An 'old tech' item", "floppy cassette vhs modem pager dialup disk walkman beeper cartridge crt tape fax pong abacus punchcard"),
("A drone or vehicle of the future", "hoverbike jetpack hovercraft maglev drone shuttle pod rocket skiff rover mech walker glider tram"),
("Something a hologram can show", "map face message menu video image model chart ghost sign movie game avatar globe puppet text clock"),
("A virtual reality word", "headset avatar world sim portal lobby haptic glove goggles immersive metaverse render gaze motion cardboard"),
("A tech company product type", "phone laptop tablet watch earbuds console camera tv speaker router drone printer monitor charger headset"),
("A computer virus symptom", "lag crash freeze pop spam slow reboot glitch error loop beep ads redirect lock leak encrypt"),
("A sci-fi weapon", "laser blaster phaser plasma railgun saber emp cannon disruptor torpedo ray stun pistol rifle grenade turret"),
("Something in a server room", "rack cable fan switch router server cooler ups cage light door lock tape tray vent monitor patch panel"),
("A 'digital' payment or money word", "bitcoin crypto token coin wallet ledger chain mint stake ether blockchain nft pay card tap app balance"),
("An alien word", "ufo saucer probe abduct beam martian alien tentacle antenna galaxy planet moon orbit invader zorg pod signal"),
("A word for a glitch in the matrix", "glitch lag bug error crash loop freeze flicker static noise skip tear stutter ghost fault corrupt"),
],
'comedy': [
("A funny sound", "boing splat honk squeak burp hiccup sneeze giggle cackle snort splash plop thud boom pop fart zing slurp whoosh quack oink moo"),
("A silly job title", "janitor clown mime plumber jester tester sniffer taster juggler wrangler jockey barista butler mascot pirate dummy stuntman"),
("Something a clown has", "nose wig shoes horn balloon pie makeup flower car bucket tie hat suspenders unicycle trick bow juggling"),
("A thing that is awkward", "silence hug wave date toast joke handshake photo dance lift stare meeting reunion blunder pause intro"),
("A funny animal", "penguin llama sloth duck goat chicken platypus pig monkey otter goose camel walrus ostrich hippo parrot hamster pug alpaca turkey"),
("A word that sounds silly", "bamboozle bumbershoot kerfuffle gobbledygook flabbergasted hullabaloo shenanigans nincompoop snickerdoodle wobble jiggle squiggle flapjack wiggle yodel noodle bonkers"),
("A thing in a prank", "whoopee cushion bucket glitter fake spider bug sticker slime balloon wrap mask paint tape rubber egg scare banana"),
("An excuse for being late", "traffic alarm bus sleep cat dog flat rain snow train queue lost fog car storm toast phone"),
("A dad joke topic", "pun socks eggs coffee chicken tools lawn grill sports skeleton scarecrow pizza math jacket bread pillow cheese"),
("A food that is funny to say", "taco noodle pickle waffle pancake meatball dumpling nugget muffin banana biscuit burrito pudding pretzel cupcake bagel gnocchi kumquat"),
("A comedy movie type", "spoof parody satire sitcom farce slapstick roast sketch buddy romcom mockumentary prank caper musical clownery"),
("Something that makes you laugh", "joke pun prank tickle clown meme sketch gag riddle blooper fail skit comic cartoon tease banter"),
("A silly walk or dance", "waddle strut shuffle moonwalk twist worm robot shimmy skip hop hobble stomp tiptoe floss stagger bounce"),
("An embarrassing thing to happen", "trip fall spill burp stutter blush sneeze fumble slip blunder stain split tangle crash forget"),
("A funny nickname", "buddy chief champ sport tiger bubba pal chuckles noodle peanut pumpkin sparky muffin bean cupcake rascal"),
("A silly hat", "fedora beanie tophat fez sombrero wizard clown crown cowboy propeller helmet bonnet visor turban bowler cone"),
("A thing a cartoon character gets hit by", "anvil piano pie boulder safe frying pan hammer bucket rake door bomb cannon truck brick banana"),
("A word for 'nonsense'", "baloney hogwash malarkey poppycock balderdash gibberish drivel bunk rubbish twaddle hooey nonsense bosh hokum humbug"),
("A silly pet name", "fluffy mittens biscuit pickles nugget waffles bean noodle meatball peanut sprout muffin pudding squeak toast"),
("A party game", "charades twister tag musical chairs limbo piñata karaoke trivia bingo pong darts hide seek simon freeze scavenger"),
("A thing that's 'hangry' related", "snack pizza taco burger fries cake chips donut noodle fridge lunch dinner candy cookie bread pasta"),
("A funny noise for an animal", "quack moo oink meow woof baa neigh cluck honk hiss roar squeal chirp ribbit buzz tweet howl bark purr"),
("Something you'd see in a cartoon", "anvil rocket rabbit mouse cat dog duck bomb rainbow cloud gag spring hole pie mallet wink"),
("A silly reason to celebrate", "pizza friday weekend nap cookie sandwich pajama donut taco socks lunch recess holiday cheese pancake"),
("A thing you'd find in a clown car", "clown horn wig shoe pie bucket balloon flower nose juggler ball hat seltzer trick banana"),
],
}
