-- Prompt packs: meme, fantasy, cyber, comedy (English). Room setting 'pack' = all | classic | meme | fantasy | cyber | comedy.
alter table prompts add column if not exists pack text not null default 'classic';

insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-1', 'A meme or internet joke', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-1');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bae based bruh cap chad cringe dank doge drip emoji fail flex fomo gif karen lit lol meme mood noob oof pepe rickroll rizz rofl salty sheesh simp stonks sus thicc troll vibe viral woke yeet yolo', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-1' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bae based bruh cap chad cringe dank doge drip emoji fail flex fomo gif karen lit lol meme mood noob oof pepe rickroll rizz rofl salty sheesh simp stonks sus thicc troll vibe viral woke yeet yolo', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-2', 'Something you do on social media', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-2');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('block cancel comment doomscroll download filter flex follow ghost hashtag like lurk mute post react reply repost scroll selfie share stream swipe tag trend troll tweet unfollow upload viral vlog', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-2' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('block cancel comment doomscroll download filter flex follow ghost hashtag like lurk mute post react reply repost scroll selfie share stream swipe tag trend troll tweet unfollow upload viral vlog', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-3', 'An emoji you spam', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-3');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alien angel angry cake clap cloud cool crown cry devil eyes fire ghost heart laugh moon party pizza poop pray rain robot rocket skull smile star sun taco wink', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-3' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alien angel angry cake clap cloud cool crown cry devil eyes fire ghost heart laugh moon party pizza poop pray rain robot rocket skull smile star sun taco wink', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-4', 'Something that is ''sus''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-4');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alibi crewmate crooked culprit dodgy eject fake fishy imposter impostor liar lie mole rat sabotage shady shifty sneak snitch spy suspect traitor trick vent vote', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-4' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alibi crewmate crooked culprit dodgy eject fake fishy imposter impostor liar lie mole rat sabotage shady shifty sneak snitch spy suspect traitor trick vent vote', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-5', 'A thing that goes viral', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-5');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('baby cat challenge clip cover dance dog duet fail filter flashmob hack meme photo post prank recipe remix skit song sound stunt trend tweet video', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-5' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('baby cat challenge clip cover dance dog duet fail filter flashmob hack meme photo post prank recipe remix skit song sound stunt trend tweet video', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-6', 'A video game everyone memes about', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-6');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('among apex celeste doom fallout fortnite hades halo mario minecraft overwatch pacman pokemon portal roblox skyrim sonic terraria tetris undertale valorant witcher zelda', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-6' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('among apex celeste doom fallout fortnite hades halo mario minecraft overwatch pacman pokemon portal roblox skyrim sonic terraria tetris undertale valorant witcher zelda', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-7', 'Something a ''boomer'' would say', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-7');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('antenna back cassette cheque dial disco fax kids landline lawn newspaper phone postcard radio rotary sonny stamp telegram typewriter vhs vinyl', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-7' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('antenna back cassette cheque dial disco fax kids landline lawn newspaper phone postcard radio rotary sonny stamp telegram typewriter vhs vinyl', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-8', 'A ''main character'' thing to do', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-8');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('coffee convertible cry dance film headphones journal laugh poetry rain rooftop run sing skyline stare sunset train walk wander window', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-8' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('coffee convertible cry dance film headphones journal laugh poetry rain rooftop run sing skyline stare sunset train walk wander window', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-9', 'A reaction in the group chat', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-9');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('based bruh cap dead ded facts fire gasp huh hype kek lmao lol mood nice nope omg oof rofl same sheesh sus wow wtf yeet yikes', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-9' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('based bruh cap dead ded facts fire gasp huh hype kek lmao lol mood nice nope omg oof rofl same sheesh sus wow wtf yeet yikes', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-10', 'Something that is ''cringe''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-10');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('awkward blush cosplay crush dad dance duet emo fedora jargon karaoke mime mullet nickname pickup poem prank pun rap selfie skit spam tiktok', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-10' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('awkward blush cosplay crush dad dance duet emo fedora jargon karaoke mime mullet nickname pickup poem prank pun rap selfie skit spam tiktok', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-11', 'A thing in a ''gamer setup''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-11');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('cable chair console controller cpu desk dock fan gpu headset joystick keyboard lamp led light mic monitor mouse mousepad router speaker stand webcam', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-11' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('cable chair console controller cpu desk dock fan gpu headset joystick keyboard lamp led light mic monitor mouse mousepad router speaker stand webcam', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-12', 'A famous internet animal', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-12');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alpaca bear bird capybara cat chonk corgi dog doge duck fish frog goat grumpy hamster husky keyboard llama otter owl panda pug seal sloth', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-12' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alpaca bear bird capybara cat chonk corgi dog doge duck fish frog goat grumpy hamster husky keyboard llama otter owl panda pug seal sloth', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-13', 'Something you ''rage quit'' over', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-13');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('boss bug camper cheater combo crash death disconnect drop fall glitch hacker lag lagspike loot loss noob ping puzzle respawn rng timeout trap', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-13' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('boss bug camper cheater combo crash death disconnect drop fall glitch hacker lag lagspike loot loss noob ping puzzle respawn rng timeout trap', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-14', 'A streamer or YouTuber thing', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-14');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bell bits channel chat clip donate emote hype intro live merch mod outro patreon raid sponsor stream sub subscribe thumbnail upload vlog vod', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-14' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bell bits channel chat clip donate emote hype intro live merch mod outro patreon raid sponsor stream sub subscribe thumbnail upload vlog vod', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-15', 'A word you''d see in a ''tier list''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-15');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bad banger best bronze cool diamond elite god gold good hot lame legend meh mid rank rated silver tier top trash worst', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-15' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bad banger best bronze cool diamond elite god gold good hot lame legend meh mid rank rated silver tier top trash worst', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-16', 'A popular snack for a movie night', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-16');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('candy cheese chips chocolate cookie cracker cupcake donut fries gummy jerky licorice marshmallow nachos pickle pizza popcorn pretzel soda taco', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-16' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('candy cheese chips chocolate cookie cracker cupcake donut fries gummy jerky licorice marshmallow nachos pickle pizza popcorn pretzel soda taco', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-17', 'A ''plot twist'' ingredient', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-17');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ally amnesia clone clue curse dream ghost heir hero letter lie mask memory portal prank reveal secret spy tape traitor twin villain', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-17' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ally amnesia clone clue curse dream ghost heir hero letter lie mask memory portal prank reveal secret spy tape traitor twin villain', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-18', 'An app on your phone', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-18');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('browser calculator calendar camera clock fitness game health mail maps messages music news notes phone photos podcast reels settings store video wallet weather', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-18' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('browser calculator calendar camera clock fitness game health mail maps messages music news notes phone photos podcast reels settings store video wallet weather', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-19', 'Something you do when bored', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-19');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('call channel clean daydream doodle doomscroll fidget flip game hum nap pace pickup read scroll sigh sleep snack stare tap text wander', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-19' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('call channel clean daydream doodle doomscroll fidget flip game hum nap pace pickup read scroll sigh sleep snack stare tap text wander', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-20', 'Slang that means ''cool''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-20');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('awesome bad boss crisp dope epic fire fresh gnarly groovy killer lit neat rad sick slick smooth swell tight tubular wicked', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-20' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('awesome bad boss crisp dope epic fire fresh gnarly groovy killer lit neat rad sick slick smooth swell tight tubular wicked', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-21', 'A reason to say ''no cap''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-21');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('certain exact fact frank honest legit plain proof real serious sincere solid straight sure swear truth', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-21' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('certain exact fact frank honest legit plain proof real serious sincere solid straight sure swear truth', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-22', 'A creature from internet horror lore', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-22');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('backrooms clown creepypasta dog doll entity ghost grinning head jeff mimic puppet rake shadow siren skinwalker slenderman smile wendigo', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-22' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('backrooms clown creepypasta dog doll entity ghost grinning head jeff mimic puppet rake shadow siren skinwalker slenderman smile wendigo', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-23', 'A thing ''NPC'' characters do', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-23');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('blink despawn follow greet guard idle loop nod patrol quest repeat sell shop sign spawn stand talk walk wander wave', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-23' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('blink despawn follow greet guard idle loop nod patrol quest repeat sell shop sign spawn stand talk walk wander wave', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-24', 'A ''trend'' from the last decade', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-24');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('avocado bottle bucket dab dalgona fidget flip floss harlem hoverboard ice latte mannequin planking pumpkin shake slime spinner tiktok toast unicorn', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-24' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('avocado bottle bucket dab dalgona fidget flip floss harlem hoverboard ice latte mannequin planking pumpkin shake slime spinner tiktok toast unicorn', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-25', 'A word you use in a hype message', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-25');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ace banger boss champ clutch crazy epic fire goat huge insane king legend lets massive perfect queen win wow yes', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-25' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ace banger boss champ clutch crazy epic fire goat huge insane king legend lets massive perfect queen win wow yes', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-meme-26', 'Something that gets ''canceled''', true, 'meme' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-meme-26');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('class concert contract date event flight game meeting order party plan season show subscription tour trip wedding', ' ')) w where p.lang = 'en' and p.key = 'pack-meme-26' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('class concert contract date event flight game meeting order party plan season show subscription tour trip wedding', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-1', 'A fantasy creature', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-1');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('banshee basilisk centaur chimera cyclops dragon dwarf elf fairy giant gnome goblin golem griffin harpy hydra imp kraken mermaid minotaur ogre orc pegasus phoenix pixie sphinx sprite troll unicorn wyvern yeti', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-1' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('banshee basilisk centaur chimera cyclops dragon dwarf elf fairy giant gnome goblin golem griffin harpy hydra imp kraken mermaid minotaur ogre orc pegasus phoenix pixie sphinx sprite troll unicorn wyvern yeti', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-2', 'A magical item', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-2');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('amulet boots chalice charm cloak crown crystal gauntlet grimoire horn lantern mirror orb potion relic ring rune scepter scroll shield staff sword talisman tome wand', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-2' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('amulet boots chalice charm cloak crown crystal gauntlet grimoire horn lantern mirror orb potion relic ring rune scepter scroll shield staff sword talisman tome wand', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-3', 'A spell or magic action', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-3');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('banish bless blink burn cast charm conjure curse dispel enchant freeze heal hex illuminate levitate shapeshift shield smite summon teleport transmute vanish ward', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-3' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('banish bless blink burn cast charm conjure curse dispel enchant freeze heal hex illuminate levitate shapeshift shield smite summon teleport transmute vanish ward', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-4', 'A place in a fantasy world', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-4');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('abbey bridge castle cave citadel crypt dungeon forest fortress glade harbor keep kingdom lair mountain realm ruin swamp tavern temple throne tower valley village', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-4' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('abbey bridge castle cave citadel crypt dungeon forest fortress glade harbor keep kingdom lair mountain realm ruin swamp tavern temple throne tower valley village', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-5', 'A fantasy hero''s weapon', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-5');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('axe blade bow club crossbow dagger flail halberd hammer lance mace rapier scimitar shield sling spear staff sword trident wand whip', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-5' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('axe blade bow club crossbow dagger flail halberd hammer lance mace rapier scimitar shield sling spear staff sword trident wand whip', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-6', 'Something in a wizard''s tower', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-6');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('book bottle candle cat cauldron chest crystal desk globe hat herb ink map mirror orb owl potion quill robe scroll skull staff telescope', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-6' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('book bottle candle cat cauldron chest crystal desk globe hat herb ink map mirror orb owl potion quill robe scroll skull staff telescope', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-7', 'A type of magic user', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-7');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alchemist bard cleric conjurer druid enchanter mage monk necromancer oracle priest sage seer shaman sorcerer summoner warlock witch wizard', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-7' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alchemist bard cleric conjurer druid enchanter mage monk necromancer oracle priest sage seer shaman sorcerer summoner warlock witch wizard', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-8', 'A dragon''s treasure', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-8');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('amulet chalice chest coin crown diamond emerald gem goblet gold hoard idol jewel medal pearl relic ring ruby sapphire silver tiara', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-8' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('amulet chalice chest coin crown diamond emerald gem goblet gold hoard idol jewel medal pearl relic ring ruby sapphire silver tiara', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-9', 'A kind of potion', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-9');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('antidote brew courage draught elixir fire frost growth healing invisibility love luck mana poison shrink sleep speed stamina strength tonic', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-9' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('antidote brew courage draught elixir fire frost growth healing invisibility love luck mana poison shrink sleep speed stamina strength tonic', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-10', 'A tavern order', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-10');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ale bacon bread broth cheese cider ham honey lager mead mutton pie porter roast rum soup stew tart wine', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-10' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ale bacon bread broth cheese cider ham honey lager mead mutton pie porter roast rum soup stew tart wine', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-11', 'A fantasy race or folk', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-11');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('centaur dragonborn dwarf elf fairy faun giant gnome goblin halfling human imp kobold nymph ogre orc satyr tiefling troll', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-11' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('centaur dragonborn dwarf elf fairy faun giant gnome goblin halfling human imp kobold nymph ogre orc satyr tiefling troll', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-12', 'A knight''s gear', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-12');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('armor banner belt boots cape crest gauntlet greaves helm horse lance mail plate saddle shield spurs sword tabard visor', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-12' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('armor banner belt boots cape crest gauntlet greaves helm horse lance mail plate saddle shield spurs sword tabard visor', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-13', 'A name for a magic school subject', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-13');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('abjuration alchemy astronomy charms conjuring divination enchanting evocation healing herbology illusion necromancy potions runes', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-13' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('abjuration alchemy astronomy charms conjuring divination enchanting evocation healing herbology illusion necromancy potions runes', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-14', 'A creature you''d find in a dark forest', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-14');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bat bear boar elk ent fox goblin hag moth owl raven snake spider sprite stag troll witch wolf wraith', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-14' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bat bear boar elk ent fox goblin hag moth owl raven snake spider sprite stag troll witch wolf wraith', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-15', 'A royal court role', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-15');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('advisor baron bishop chancellor cupbearer duke earl herald jester king knight marshal page prince princess queen regent squire steward', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-15' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('advisor baron bishop chancellor cupbearer duke earl herald jester king knight marshal page prince princess queen regent squire steward', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-16', 'A quest item', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-16');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('amulet chalice crown egg feather gem horn idol key lantern map orb potion relic ring rune scroll shield sword', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-16' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('amulet chalice crown egg feather gem horn idol key lantern map orb potion relic ring rune scroll shield sword', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-17', 'Something an elf might be good at', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-17');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('archery climbing crafting dancing forestry healing herbs magic music poetry riding singing stealth tracking wisdom', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-17' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('archery climbing crafting dancing forestry healing herbs magic music poetry riding singing stealth tracking wisdom', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-18', 'A fantasy beast you can ride', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-18');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bear boar camel dragon drake eagle elk griffin hippogriff horse mammoth pegasus stag unicorn wolf wyvern', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-18' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bear boar camel dragon drake eagle elk griffin hippogriff horse mammoth pegasus stag unicorn wolf wyvern', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-19', 'A thing found in a dungeon', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-19');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('altar bone cell chain chest coffin door key lever ooze puzzle rat rune skeleton spider stairs throne torch trap', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-19' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('altar bone cell chain chest coffin door key lever ooze puzzle rat rune skeleton spider stairs throne torch trap', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-20', 'A dark lord''s minion', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-20');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bat cultist demon ghoul goblin imp orc skeleton specter spider troll witch wolf wraith zombie', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-20' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bat cultist demon ghoul goblin imp orc skeleton specter spider troll witch wolf wraith zombie', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-21', 'A magical element', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-21');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('air arcane earth fire frost ice light lightning metal nature shadow spirit storm thunder void water wind', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-21' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('air arcane earth fire frost ice light lightning metal nature shadow spirit storm thunder void water wind', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-22', 'A mythical place', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-22');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('asgard atlantis avalon camelot eden elysium hades nirvana oasis olympus shangrila tartarus utopia valhalla', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-22' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('asgard atlantis avalon camelot eden elysium hades nirvana oasis olympus shangrila tartarus utopia valhalla', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-23', 'Something a bard does', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-23');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('compose dance hum joke juggle lute perform play recite rhyme sing story strum tale tell verse whistle', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-23' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('compose dance hum joke juggle lute perform play recite rhyme sing story strum tale tell verse whistle', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-24', 'A fairy tale object', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-24');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('apple beanstalk castle crown gingerbread glass lamp mirror poison pumpkin rose slipper spindle thorn tower', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-24' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('apple beanstalk castle crown gingerbread glass lamp mirror poison pumpkin rose slipper spindle thorn tower', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-fantasy-25', 'A word about a quest or adventure', true, 'fantasy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-fantasy-25');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('battle crusade expedition glory hunt journey march mission odyssey peril raid riddle siege treasure trek trial voyage', ' ')) w where p.lang = 'en' and p.key = 'pack-fantasy-25' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('battle crusade expedition glory hunt journey march mission odyssey peril raid riddle siege treasure trek trial voyage', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-1', 'A piece of computer hardware', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-1');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('battery cable charger chip cpu disk drive fan gpu keyboard modem monitor motherboard mouse port printer ram router scanner server speaker switch webcam', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-1' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('battery cable charger chip cpu disk drive fan gpu keyboard modem monitor motherboard mouse port printer ram router scanner server speaker switch webcam', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-2', 'A programming word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-2');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('api array branch bug class code commit compile debug function list loop merge module node queue script sort stack string syntax tree variable', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-2' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('api array branch bug class code commit compile debug function list loop merge module node queue script sort stack string syntax tree variable', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-3', 'A thing hackers do', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-3');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('boot breach bypass crack decrypt encrypt exploit hack infiltrate inject leak phish probe pwn scan sniff spoof steal trace', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-3' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('boot breach bypass crack decrypt encrypt exploit hack infiltrate inject leak phish probe pwn scan sniff spoof steal trace', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-4', 'A cyberpunk gadget', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-4');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('arm blade chip cyberdeck drone eye glove goggles hologram hoverbike implant jack link mask neon spike visor wires', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-4' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('arm blade chip cyberdeck drone eye glove goggles hologram hoverbike implant jack link mask neon spike visor wires', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-5', 'Something about the internet', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-5');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bandwidth browser cache chat cloud cookie domain download email host link packet page router server site stream upload web wifi', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-5' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bandwidth browser cache chat cloud cookie domain download email host link packet page router server site stream upload web wifi', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-6', 'A robot or AI word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-6');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('algorithm android bot circuit core cyborg droid drone engine logic machine mech neural program robot sensor servo', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-6' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('algorithm android bot circuit core cyborg droid drone engine logic machine mech neural program robot sensor servo', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-7', 'A sci-fi spaceship part', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-7');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('airlock bay beacon bridge cannon cargo cockpit console dock engine fuel hatch hull nozzle radar reactor shield thruster wing', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-7' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('airlock bay beacon bridge cannon cargo cockpit console dock engine fuel hatch hull nozzle radar reactor shield thruster wing', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-8', 'A security term', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-8');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alarm antivirus auth badge cipher encrypt firewall key lock login malware password patch proxy secure token trojan virus vpn worm', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-8' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alarm antivirus auth badge cipher encrypt firewall key lock login malware password patch proxy secure token trojan virus vpn worm', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-9', 'A futuristic city thing', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-9');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alley arcade billboard drone elevator grid hover megacorp monorail neon plaza skyline skyway slum sprawl station tower tunnel', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-9' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alley arcade billboard drone elevator grid hover megacorp monorail neon plaza skyline skyway slum sprawl station tower tunnel', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-10', 'A data or file word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-10');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('archive backup bin bit byte cache data disk drive file folder format index log record sector table zip', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-10' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('archive backup bin bit byte cache data disk drive file folder format index log record sector table zip', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-11', 'A gaming-tech term', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-11');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('avatar cutscene engine fps frame hitbox lag level loot mod patch ping pixel polygon render shader spawn sprite texture', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-11' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('avatar cutscene engine fps frame hitbox lag level loot mod patch ping pixel polygon render shader spawn sprite texture', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-12', 'A thing on a keyboard', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-12');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alt arrow backspace caps control delete end enter escape function home insert key letter number return shift space tab', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-12' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alt arrow backspace caps control delete end enter escape function home insert key letter number return shift space tab', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-13', 'A network word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-13');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('cable client dns gateway hop host hub lan link mesh node packet ping port proxy router server switch wan', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-13' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('cable client dns gateway hop host hub lan link mesh node packet ping port proxy router server switch wan', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-14', 'A cyber crime or scam', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-14');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('breach catfish clone extortion fake fraud hijack leak phishing ransom scam skimming spam spoof swindle theft', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-14' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('breach catfish clone extortion fake fraud hijack leak phishing ransom scam skimming spam spoof swindle theft', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-15', 'An ''old tech'' item', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-15');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('abacus beeper cartridge cassette crt dialup disk fax floppy modem pager pong punchcard tape vhs walkman', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-15' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('abacus beeper cartridge cassette crt dialup disk fax floppy modem pager pong punchcard tape vhs walkman', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-16', 'A drone or vehicle of the future', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-16');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('drone glider hoverbike hovercraft jetpack maglev mech pod rocket rover shuttle skiff tram walker', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-16' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('drone glider hoverbike hovercraft jetpack maglev mech pod rocket rover shuttle skiff tram walker', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-17', 'Something a hologram can show', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-17');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('avatar chart clock face game ghost globe image map menu message model movie puppet sign text video', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-17' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('avatar chart clock face game ghost globe image map menu message model movie puppet sign text video', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-18', 'A virtual reality word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-18');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('avatar cardboard gaze glove goggles haptic headset immersive lobby metaverse motion portal render sim world', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-18' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('avatar cardboard gaze glove goggles haptic headset immersive lobby metaverse motion portal render sim world', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-19', 'A tech company product type', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-19');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('camera charger console drone earbuds headset laptop monitor phone printer router speaker tablet watch', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-19' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('camera charger console drone earbuds headset laptop monitor phone printer router speaker tablet watch', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-20', 'A computer virus symptom', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-20');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ads beep crash encrypt error freeze glitch lag leak lock loop pop reboot redirect slow spam', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-20' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ads beep crash encrypt error freeze glitch lag leak lock loop pop reboot redirect slow spam', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-21', 'A sci-fi weapon', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-21');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('blaster cannon disruptor emp grenade laser phaser pistol plasma railgun ray rifle saber stun torpedo turret', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-21' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('blaster cannon disruptor emp grenade laser phaser pistol plasma railgun ray rifle saber stun torpedo turret', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-22', 'Something in a server room', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-22');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('cable cage cooler door fan light lock monitor panel patch rack router server switch tape tray ups vent', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-22' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('cable cage cooler door fan light lock monitor panel patch rack router server switch tape tray ups vent', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-23', 'A ''digital'' payment or money word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-23');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('app balance bitcoin blockchain card chain coin crypto ether ledger mint nft pay stake tap token wallet', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-23' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('app balance bitcoin blockchain card chain coin crypto ether ledger mint nft pay stake tap token wallet', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-24', 'An alien word', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-24');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('abduct alien antenna beam galaxy invader martian moon orbit planet pod probe saucer signal tentacle ufo zorg', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-24' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('abduct alien antenna beam galaxy invader martian moon orbit planet pod probe saucer signal tentacle ufo zorg', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-cyber-25', 'A word for a glitch in the matrix', true, 'cyber' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-cyber-25');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bug corrupt crash error fault flicker freeze ghost glitch lag loop noise skip static stutter tear', ' ')) w where p.lang = 'en' and p.key = 'pack-cyber-25' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bug corrupt crash error fault flicker freeze ghost glitch lag loop noise skip static stutter tear', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-1', 'A funny sound', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-1');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('boing boom burp cackle fart giggle hiccup honk moo oink plop pop quack slurp sneeze snort splash splat squeak thud whoosh zing', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-1' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('boing boom burp cackle fart giggle hiccup honk moo oink plop pop quack slurp sneeze snort splash splat squeak thud whoosh zing', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-2', 'A silly job title', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-2');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('barista butler clown dummy janitor jester jockey juggler mascot mime pirate plumber sniffer stuntman taster tester wrangler', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-2' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('barista butler clown dummy janitor jester jockey juggler mascot mime pirate plumber sniffer stuntman taster tester wrangler', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-3', 'Something a clown has', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-3');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('balloon bow bucket car flower hat horn juggling makeup nose pie shoes suspenders tie trick unicycle wig', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-3' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('balloon bow bucket car flower hat horn juggling makeup nose pie shoes suspenders tie trick unicycle wig', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-4', 'A thing that is awkward', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-4');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('blunder dance date handshake hug intro joke lift meeting pause photo reunion silence stare toast wave', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-4' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('blunder dance date handshake hug intro joke lift meeting pause photo reunion silence stare toast wave', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-5', 'A funny animal', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-5');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alpaca camel chicken duck goat goose hamster hippo llama monkey ostrich otter parrot penguin pig platypus pug sloth turkey walrus', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-5' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alpaca camel chicken duck goat goose hamster hippo llama monkey ostrich otter parrot penguin pig platypus pug sloth turkey walrus', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-6', 'A word that sounds silly', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-6');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bamboozle bonkers bumbershoot flabbergasted flapjack gobbledygook hullabaloo jiggle kerfuffle nincompoop noodle shenanigans snickerdoodle squiggle wiggle wobble yodel', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-6' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bamboozle bonkers bumbershoot flabbergasted flapjack gobbledygook hullabaloo jiggle kerfuffle nincompoop noodle shenanigans snickerdoodle squiggle wiggle wobble yodel', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-7', 'A thing in a prank', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-7');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('balloon banana bucket bug cushion egg fake glitter mask paint rubber scare slime spider sticker tape whoopee wrap', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-7' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('balloon banana bucket bug cushion egg fake glitter mask paint rubber scare slime spider sticker tape whoopee wrap', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-8', 'An excuse for being late', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-8');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('alarm bus car cat dog flat fog lost phone queue rain sleep snow storm toast traffic train', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-8' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('alarm bus car cat dog flat fog lost phone queue rain sleep snow storm toast traffic train', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-9', 'A dad joke topic', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-9');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bread cheese chicken coffee eggs grill jacket lawn math pillow pizza pun scarecrow skeleton socks sports tools', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-9' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bread cheese chicken coffee eggs grill jacket lawn math pillow pizza pun scarecrow skeleton socks sports tools', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-10', 'A food that is funny to say', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-10');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bagel banana biscuit burrito cupcake dumpling gnocchi kumquat meatball muffin noodle nugget pancake pickle pretzel pudding taco waffle', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-10' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bagel banana biscuit burrito cupcake dumpling gnocchi kumquat meatball muffin noodle nugget pancake pickle pretzel pudding taco waffle', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-11', 'A comedy movie type', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-11');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('buddy caper clownery farce mockumentary musical parody prank roast romcom satire sitcom sketch slapstick spoof', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-11' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('buddy caper clownery farce mockumentary musical parody prank roast romcom satire sitcom sketch slapstick spoof', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-12', 'Something that makes you laugh', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-12');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('banter blooper cartoon clown comic fail gag joke meme prank pun riddle sketch skit tease tickle', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-12' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('banter blooper cartoon clown comic fail gag joke meme prank pun riddle sketch skit tease tickle', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-13', 'A silly walk or dance', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-13');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bounce floss hobble hop moonwalk robot shimmy shuffle skip stagger stomp strut tiptoe twist waddle worm', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-13' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bounce floss hobble hop moonwalk robot shimmy shuffle skip stagger stomp strut tiptoe twist waddle worm', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-14', 'An embarrassing thing to happen', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-14');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('blunder blush burp crash fall forget fumble slip sneeze spill split stain stutter tangle trip', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-14' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('blunder blush burp crash fall forget fumble slip sneeze spill split stain stutter tangle trip', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-15', 'A funny nickname', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-15');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bean bubba buddy champ chief chuckles cupcake muffin noodle pal peanut pumpkin rascal sparky sport tiger', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-15' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bean bubba buddy champ chief chuckles cupcake muffin noodle pal peanut pumpkin rascal sparky sport tiger', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-16', 'A silly hat', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-16');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('beanie bonnet bowler clown cone cowboy crown fedora fez helmet propeller sombrero tophat turban visor wizard', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-16' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('beanie bonnet bowler clown cone cowboy crown fedora fez helmet propeller sombrero tophat turban visor wizard', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-17', 'A thing a cartoon character gets hit by', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-17');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('anvil banana bomb boulder brick bucket cannon door frying hammer pan piano pie rake safe truck', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-17' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('anvil banana bomb boulder brick bucket cannon door frying hammer pan piano pie rake safe truck', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-18', 'A word for ''nonsense''', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-18');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('balderdash baloney bosh bunk drivel gibberish hogwash hokum hooey humbug malarkey nonsense poppycock rubbish twaddle', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-18' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('balderdash baloney bosh bunk drivel gibberish hogwash hokum hooey humbug malarkey nonsense poppycock rubbish twaddle', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-19', 'A silly pet name', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-19');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bean biscuit fluffy meatball mittens muffin noodle nugget peanut pickles pudding sprout squeak toast waffles', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-19' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bean biscuit fluffy meatball mittens muffin noodle nugget peanut pickles pudding sprout squeak toast waffles', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-20', 'A party game', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-20');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ata bingo chairs charades darts freeze hide karaoke limbo musical pong scavenger seek simon tag trivia twister', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-20' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ata bingo chairs charades darts freeze hide karaoke limbo musical pong scavenger seek simon tag trivia twister', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-21', 'A thing that''s ''hangry'' related', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-21');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('bread burger cake candy chips cookie dinner donut fridge fries lunch noodle pasta pizza snack taco', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-21' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('bread burger cake candy chips cookie dinner donut fridge fries lunch noodle pasta pizza snack taco', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-22', 'A funny noise for an animal', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-22');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('baa bark buzz chirp cluck hiss honk howl meow moo neigh oink purr quack ribbit roar squeal tweet woof', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-22' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('baa bark buzz chirp cluck hiss honk howl meow moo neigh oink purr quack ribbit roar squeal tweet woof', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-23', 'Something you''d see in a cartoon', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-23');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('anvil bomb cat cloud dog duck gag hole mallet mouse pie rabbit rainbow rocket spring wink', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-23' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('anvil bomb cat cloud dog duck gag hole mallet mouse pie rabbit rainbow rocket spring wink', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-24', 'A silly reason to celebrate', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-24');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('cheese cookie donut friday holiday lunch nap pajama pancake pizza recess sandwich socks taco weekend', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-24' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('cheese cookie donut friday holiday lunch nap pajama pancake pizza recess sandwich socks taco weekend', ' ')) w on conflict do nothing;
insert into prompts (lang, key, text, active, pack) select 'en', 'pack-comedy-25', 'A thing you''d find in a clown car', true, 'comedy' where not exists (select 1 from prompts where lang = 'en' and key = 'pack-comedy-25');
insert into prompt_words (prompt_id, word) select p.id, w from prompts p, unnest(string_to_array('ball balloon banana bucket clown flower hat horn juggler nose pie seltzer shoe trick wig', ' ')) w where p.lang = 'en' and p.key = 'pack-comedy-25' on conflict do nothing;
insert into words (lang, word) select 'en', w from unnest(string_to_array('ball balloon banana bucket clown flower hat horn juggler nose pie seltzer shoe trick wig', ' ')) w on conflict do nothing;

create or replace function _pick_prompt(p_room_id uuid) returns bigint
language plpgsql security definer set search_path = public as $$
declare v_room rooms; v_lang text; v_prompt bigint; v_pack text;
begin
  select * into v_room from rooms where id = p_room_id;
  v_lang := coalesce(v_room.settings->>'lang', 'en');
  v_pack := case when v_lang = 'en' then coalesce(v_room.settings->>'pack', 'all') else 'all' end;
  select id into v_prompt from prompts
    where active and lang = v_lang and (v_pack = 'all' or pack = v_pack) and not (id = any(v_room.used_prompts)) order by random() limit 1;
  if v_prompt is null then
    select id into v_prompt from prompts where active and lang = v_lang and (v_pack = 'all' or pack = v_pack) order by random() limit 1;
  end if;
  if v_prompt is null then   -- language has no prompts loaded yet: fall back to English
    select id into v_prompt from prompts where active and lang = 'en' order by random() limit 1;
  end if;
  return v_prompt;
end $$;


create or replace function update_settings(p_token uuid, p_settings jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_me players; v_room rooms; v_cur jsonb; v_in jsonb := coalesce(p_settings, '{}'::jsonb); v_new jsonb; v_count int;
  v_mode text; v_size int;
begin
  v_me := _me(p_token);
  select * into v_room from rooms where id = v_me.room_id for update;
  if v_room.host_id <> v_me.id then raise exception 'NOT_HOST'; end if;
  if v_room.phase <> 'lobby' then raise exception 'WRONG_PHASE'; end if;
  v_cur := _defaults() || v_room.settings;
  select count(*) into v_count from players where room_id = v_room.id;
  v_mode := case when v_in->>'mode' in ('classic', 'duel', 'team') then v_in->>'mode' else v_cur->>'mode' end;
  v_size := _clamp(coalesce(v_in->'team_size', v_cur->'team_size'), 2, 3, 2);
  if v_mode = 'duel' and v_count > 2 then raise exception 'TOO_MANY_FOR_DUEL'; end if;
  if v_mode = 'team' and v_count > 2 * v_size then raise exception 'TOO_MANY_FOR_TEAM'; end if;
  v_new := jsonb_build_object(
    'mode', v_mode,
    'max_players',    case when v_mode = 'duel' then 2
                           when v_mode = 'team' then 2 * v_size
                           else _clamp(coalesce(v_in->'max_players', case when v_cur->>'mode' <> 'classic' then '8'::jsonb else v_cur->'max_players' end),
                                       greatest(2, v_count), 12, 8) end,
    'answer_seconds', _clamp(coalesce(v_in->'answer_seconds', v_cur->'answer_seconds'), 10, 120, 60),
    'guess_seconds',  _clamp(coalesce(v_in->'guess_seconds', v_cur->'guess_seconds'), 8, 45, 20),
    'react_seconds',  _clamp(coalesce(v_in->'react_seconds', v_cur->'react_seconds'), 4, 20, 8),
    'duel_seconds',   _clamp(coalesce(v_in->'duel_seconds', v_cur->'duel_seconds'), 10, 60, 20),
    'strikes',        _clamp(coalesce(v_in->'strikes', v_cur->'strikes'), 1, 3, 2),
    'shrink', case when jsonb_typeof(v_in->'shrink') = 'boolean' then v_in->'shrink' else v_cur->'shrink' end,
    'cards',  case when jsonb_typeof(v_in->'cards') = 'boolean' then v_in->'cards' else v_cur->'cards' end,
    'perks',  case when jsonb_typeof(v_in->'perks') = 'boolean' then v_in->'perks' else v_cur->'perks' end,
    'lang',   case when v_in->>'lang' in ('en', 'es', 'fr', 'de', 'ja', 'zh') then v_in->>'lang'
                   else coalesce(v_cur->>'lang', 'en') end,
    'twist',  case when v_in->>'twist' in ('none', 'reverse', 'chaos', 'memory') then v_in->>'twist' else coalesce(v_cur->>'twist', 'none') end,
    'pack',  case when v_in->>'pack' in ('all', 'classic', 'meme', 'fantasy', 'cyber', 'comedy') then v_in->>'pack' else coalesce(v_cur->>'pack', 'all') end,
    'ultimates', case when jsonb_typeof(v_in->'ultimates') = 'boolean' then v_in->'ultimates' else coalesce(v_cur->'ultimates', 'false'::jsonb) end,
    'team_size', v_size,
    'rounds', _clamp(coalesce(v_in->'rounds', v_cur->'rounds'), 1, 8, 5)
  );
  update rooms set settings = v_new where id = v_room.id;
  if v_mode = 'team' then
    perform _team_setup(v_room.id);
  else
    delete from teams where room_id = v_room.id;
  end if;
  perform _bump(v_room.id, 'settings');
  return v_new;
end $$;

